services:
  database:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: UserService
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
  webapi:
    build: .
    ports:
      - "7026:7026"
    depends_on:
      - database
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:7026"
      ConnectionStrings__UserServiceConnection: "Host=database;Port=5432;Database=UserService;Username=postgres;Password=qwerty123;"
    networks:
      - backend

volumes:
  db-data:

networks:
  backend: